Add MPI library
Otherwise compiling the test fails with

  /usr/bin/ld: nonoverlappingcouplingtest_mpi-nonoverlappingcouplingtest.o: undefined reference to symbol 'MPI_Waitany'
  //usr/lib/libmpi.so.1: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status